var searchData=
[
  ['language',['Language',['../class_windows_1_1_globalization_1_1_language.html',1,'Windows::Globalization']]],
  ['launchactivatedeventargs',['LaunchActivatedEventArgs',['../class_windows_1_1_application_model_1_1_activation_1_1_launch_activated_event_args.html',1,'Windows::ApplicationModel::Activation']]],
  ['launcher',['Launcher',['../class_windows_1_1_system_1_1_launcher.html',1,'Windows::System']]],
  ['layout',['Layout',['../class_saladillo_fit_1_1_droid_1_1_resource_1_1_layout.html',1,'SaladilloFit::Droid::Resource']]],
  ['leavingbackgroundeventargs',['LeavingBackgroundEventArgs',['../class_windows_1_1_application_model_1_1_leaving_background_event_args.html',1,'Windows::ApplicationModel']]],
  ['leavingbackgroundeventhandler_5f_5fimpl',['LeavingBackgroundEventHandler__Impl',['../class_windows_1_1_u_i_1_1_xaml_1_1_leaving_background_event_handler_____impl.html',1,'Windows::UI::Xaml']]],
  ['lengthisattribute',['LengthIsAttribute',['../class_windows_1_1_foundation_1_1_metadata_1_1_length_is_attribute.html',1,'Windows::Foundation::Metadata']]],
  ['listview',['ListView',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_list_view.html',1,'Windows::UI::Xaml::Controls']]],
  ['listviewbase',['ListViewBase',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_list_view_base.html',1,'Windows::UI::Xaml::Controls']]],
  ['listviewbaseheaderitem',['ListViewBaseHeaderItem',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_list_view_base_header_item.html',1,'Windows::UI::Xaml::Controls']]],
  ['listviewheaderitem',['ListViewHeaderItem',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_list_view_header_item.html',1,'Windows::UI::Xaml::Controls']]],
  ['listviewitem',['ListViewItem',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_list_view_item.html',1,'Windows::UI::Xaml::Controls']]],
  ['listviewitempresenter',['ListViewItemPresenter',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_primitives_1_1_list_view_item_presenter.html',1,'Windows::UI::Xaml::Controls::Primitives']]],
  ['listviewitemtemplatesettings',['ListViewItemTemplateSettings',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_primitives_1_1_list_view_item_template_settings.html',1,'Windows::UI::Xaml::Controls::Primitives']]],
  ['loadcompletedeventhandler_5f_5fimpl',['LoadCompletedEventHandler__Impl',['../class_windows_1_1_u_i_1_1_xaml_1_1_navigation_1_1_load_completed_event_handler_____impl.html',1,'Windows::UI::Xaml::Navigation']]],
  ['losingfocuseventargs',['LosingFocusEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_losing_focus_event_args.html',1,'Windows::UI::Xaml::Input']]]
];
